name: context demo

on:
  workflow_dispatch:
    inputs:
      text:
        description: 'enter the word you want to print'
        default: 'Hello'
        required: true  # mandatory parameter (true is assign here that means)
        type: string

env:
  firstName: 'Anmol'
  website: 'tetsing mini bytes'

jobs:
  contexts-dmeo: # job 1
    runs-on: ${{matix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:

      - run: echo ${{ inputs.text }}
      - run: echo ${{ github.event.inputs.text }}
      - run: echo ${{ github.actor }}
      - run: echo 'Hi ${{ env.firstName }}'
      - run: echo 'website - ${{ env.website }}'
      - run: echo ${{job.status}}
      - run: echo ${{ runner.os }}
      - run: echo ${{ secrets.PASSWORD }} ${{ env.firstName }} # preference to LOCAL envvariable first
        env:
          firstName: 'Testing' #local environment variable 
  
  contexts-dmeo2: # job 2
    needs: [contexts-dmeo] # dependent on 1st job
    runs-on: ubuntu-latest

